# Generated by Django 2.2.16 on 2022-12-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221202_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
