# Generated by Django 2.2.16 on 2022-12-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20221204_1422'),
        ('reviews', '0003_delete_user'),
    ]

    operations = [
    ]
